### ISSUE TITLE
WARNING: NSWindow drag regions should only be invalidated on the Main Thread!

### ISSUE THREAD

**Issue by s2n-Gribbly** [samclane/Discordia#1]
Hey, I know you are just working on this now, and I'm watching keenly :D

There appears to be an issue, and I know it's Mac related, but thought I'd let you know. Apple is only allowing UI functionality to be used in the main thread as of 10.14: https://developer.apple.com/documentation/code_diagnostics/main_thread_checker

I will take a look at running on Ubnt or something else!

**Comment by samclane** [comment]
Thanks for checking the game out!

Mac enforcing that standard is really strange. I understand their reasoning, and I should fix that bug anyway.

**Comment by s2n-Gribbly** [comment]
Looking forward to seeing how it develops!

It got further, but I'm thinking I should give up on Mac:

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 92, in add_signal_handler
    signal.set_wakeup_fd(self._csock.fileno())
ValueError: set_wakeup_fd only works in main thread

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/plambert/Discordia/lib/python3.7/site-packages/discord/client.py", line 540, in run
    loop.add_signal_handler(signal.SIGINT, lambda: loop.stop())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 94, in add_signal_handler
    raise RuntimeError(str(exc))
RuntimeError: set_wakeup_fd only works in main thread
