### ISSUE TITLE
ImportError: libcblas.so.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ctnightmare** [samclane/Discordia#5]
I have installed everything using sudo and I am running python 3.7.

Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from Discordia.Interface.Rendering.DesktopApp import WindowRenderer, update_display
  File "/home/pi/Bot/Discordia/Discordia/Interface/Rendering/DesktopApp.py", line 12, in <module>
    import pixelhouse as ph
  File "/usr/local/lib/python3.7/dist-packages/pixelhouse/__init__.py", line 2, in <module>
    from .canvas import Canvas, load
  File "/usr/local/lib/python3.7/dist-packages/pixelhouse/canvas.py", line 2, in <module>
    import cv2
  File "/usr/local/lib/python3.7/dist-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libcblas.so.3: cannot open shared object file: No such file or directory

**Comment by ctnightmare** [comment]
sudo apt-get install libatlas-base-dev
